# Generated by Django 3.0.8 on 2020-07-06 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='targetDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 6, 17, 30, 14, 375545)),
        ),
    ]
