# Generated by Django 3.0.8 on 2020-07-06 20:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0002_auto_20200706_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='targetDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 6, 22, 25, 8, 820480)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='userid',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
