# Generated by Django 3.0.8 on 2020-07-06 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20200706_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='userid',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='todo',
            name='targetDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 6, 22, 25, 50, 756277)),
        ),
    ]
