# Generated by Django 3.0.8 on 2020-07-06 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20200706_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='targetDate',
            field=models.DateField(default=datetime.datetime(2020, 7, 6, 22, 32, 53, 761393)),
        ),
    ]
